name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          py -m pip install pyinstaller pyperclip

      - name: Build EXE with PyInstaller
        run: >
          py -m PyInstaller --noconsole --onefile --windowed
          --name "PasswordManager"
          --add-data "logo.png;."
          --add-data "data.json;."
          main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-manager-exe
          path: dist/*
